# Generated by Django 3.1.2 on 2021-01-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210116_0357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyService',
        ),
    ]
