# Generated by Django 3.1.2 on 2021-01-06 19:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='ResumeProfile',
        ),
    ]
