# Generated by Django 3.1.2 on 2021-01-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activity'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name_plural': 'Certification'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name_plural': 'Reference'},
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='resume.resumeprofile')),
            ],
            options={
                'verbose_name_plural': 'Expertise',
            },
        ),
    ]
