# Generated by Django 3.1.2 on 2021-01-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210107_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeprofile',
            options={'verbose_name_plural': 'ResumeProfile'},
        ),
    ]
