# Generated by Django 3.1.2 on 2021-01-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210107_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='Name of an institution', max_length=100)),
                ('location', models.CharField(help_text='Location of the institution', max_length=100)),
                ('course', models.CharField(help_text='Name of a course', max_length=200)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.resumeprofile')),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
    ]
