# Generated by Django 3.1.2 on 2021-01-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_skill_skillcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'SkillCategory'},
        ),
    ]
