# Generated by Django 3.1.2 on 2021-01-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name_plural': 'reference'},
        ),
    ]
