# Generated by Django 3.1.2 on 2021-01-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name_plural': 'certification'},
        ),
    ]
