# Generated by Django 3.1.2 on 2021-01-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfilePricture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_picture', to='resume.resumeprofile')),
            ],
            options={
                'verbose_name_plural': 'ResumeProfilePricture',
            },
        ),
    ]
