# Generated by Django 3.1.2 on 2021-01-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_resumeprofilepricture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeprofilepricture',
            name='title',
            field=models.CharField(help_text='Name of the picture', max_length=100),
        ),
    ]
