# Generated by Django 3.1.2 on 2021-01-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_projectpricture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertificatePricture',
            new_name='CertificatePicture',
        ),
        migrations.RenameModel(
            old_name='ProjectPricture',
            new_name='ProjectPicture',
        ),
        migrations.RenameModel(
            old_name='ResumeProfilePricture',
            new_name='ResumeProfilePicture',
        ),
    ]
