# Generated by Django 3.1.2 on 2021-01-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_auto_20210108_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
