# Generated by Django 3.1.2 on 2021-01-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_resumeprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeprofile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
